timeout: 0
quiet: yes
serial: yes
/Archipelago
    protocol: limine
    kaslr: no
    path: boot():/boot/kernel.elf
    cmdline: shell
    module_path: boot():/boot/init.bin
    module_string: init
    module_path: boot():/boot/initrd.tar
    module_string: initrd
