timeout: 0
quiet: yes
serial: yes
/Archipelago
    protocol: limine
    kaslr: no
    path: boot():/boot/kernel.elf
    cmdline: shell
    module_path: boot():/boot/init.elf
    module_string: init
    module_path: boot():/boot/selftest.elf
    module_string: selftest
    module_path: boot():/boot/echo.elf
    module_string: echo
