#pragma once

#define ARCH_X86 1

#define CONFIG_CPU_CACHE_LINE_SIZE 64

#define CONFIG_MAX_CORES 16
#define CONFIG_KERNEL_VERSION "0.0.1"
#define CONFIG_LOG_MAX_DEVICES 8

#define KERNEL_ASSERT_HANG 1
#define KERNEL_ASSERT 1

#define CONFIG_KERNEL_LOG_COLORS 1
#define CONFIG_KERNEL_TESTING 1

// Testing overrides

#if CONFIG_KERNEL_TESTING
#undef CONFIG_KERNEL_LOG_COLORS
#define CONFIG_KERNEL_LOG_COLORS 0
#endif